### ISSUE TITLE
bug: variables list is causing a misconfiguration in the UI variables section 

### ISSUE THREAD

**Issue by rivanfebrian123** [ydataai/ydata-profiling#1194]
### Current Behaviour

![图片](https://user-images.githubusercontent.com/6300910/205256319-ec83eae5-4f03-4798-805a-16401939e692.png)

### Expected Behaviour

It would be easier on eyes if we make it as pill buttons instead, just like the one in "Overview"

![图片](https://user-images.githubusercontent.com/6300910/205256854-ffd12ab0-a561-45d8-972a-88391ac9278f.png)

**Example:**

![图片](https://user-images.githubusercontent.com/6300910/205261794-cce91873-78e1-495d-af5d-6f0573f17a42.png)

### Data Description

https://pandas-profiling.ydata.ai/examples/master/features/united_report.html

### pandas-profiling version

vdev

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
@rivanfebrian123 You can change the colour of your graphics through the configuration file. I'm happy to help you in case it is needed. But it is not a requirement to have the graphics with the same color as the text, but rather a user configuration.

**Comment by rivanfebrian123** [comment]
> and open a new one for the change request for the overview buttons?

Sure, but maybe later

**Comment by g-kabra** [comment]
Hey @fabclmnt ! I've introduced this feature, and have some background on the same. I'll try taking this issue up and see if I can follow it through to closure.

**Comment by fabclmnt** [comment]
@g-kabra than you! Yes, that would be appreciated :)

**Comment by rivanfebrian123** [comment]
Hi @g-kabra . Thank you so much for fixing that cosmetic problem.

@fabclmnt About the UI request, I'd like to make a whole new design concept for Pandas Profiling. Hope it will make data analytics fun again.

**Comment by g-kabra** [comment]
Should I create a PR with the UI being as in the screenshot? Or are there any changes required as far as the basic problem was concerned? @fabclmnt

**Comment by fabclmnt** [comment]
@g-kabra yes please go ahead! This is a great improvement in the experience.

**Comment by fabclmnt** [comment]
This was solved in the last release [v4.1.0](https://github.com/ydataai/ydata-profiling/releases/tag/v4.1.0)
