### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by frbelotto** [ydataai/ydata-profiling#1237]
### Missing functionality

Missing support for python 3.11

### Proposed feature

Develop support for python 3.11, given that 3.11 is on road for some time and delivers some relevant performance upgrades.

### Additional context

Hello guys,
Any ETC for supporting python 3.11?
I´ve been facing some errors when trying to import pandas profiling (cannot import name 'DataError' from 'pandas.core.base'), and after some research I´ve found that is related to my current python version.

**Comment by kenf1** [comment]
Looking at the error log, the last line that was run prior to getting this error is `<a href='file:///---/pandas_profiling/model/correlations.py?line=12'>13`

[Line 15](https://github.com/ydataai/pandas-profiling/blob/bfe46a141435354081246d27bf94c26f4d26789f/src/pandas_profiling/model/correlations.py#L15) in `src/pandas_profiling/model/correlations.py` is what is causing this error.

Opened pull request: #1239

**Comment by aquemy** [comment]
The PR to support Python 3.11 has been merged (https://github.com/ydataai/ydata-profiling/pull/1273)

The support will be available from the next release (4.1.0).

**Comment by pirocv** [comment]
Hi,
I tried to install the latest version with conda/mamba, but I could not.
The error message shows the following.

```shell
$ mamba install -c conda-forge ydata-profiling=4.1.2

Looking for: ['ydata-profiling=4.1.2']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.11.*

Could not solve for environment specs
The following package could not be installed
└─ ydata-profiling 4.1.2**  is installable and it requires
   └─ python >=3.7,<3.11 , which can be installed.
``` 

It is the same with conda.

**Comment by sheershsaxena** [comment]
How to solve this problem which occurred when I was trying to generate a html file using pandas profiling:
cannot import name 'DataError' from 'pandas.core.base'
