### ISSUE TITLE
Bug Report: description_set["correlations"] not including all correlation coefficients.

### ISSUE THREAD

**Issue by kaijensen1** [ydataai/ydata-profiling#1261]
### Current Behaviour

 profile.description_set["correlations"] does not return all of the correlation metrics.
 
The output I received was:

dict_keys(['auto'])

### Expected Behaviour

From your documentation page https://ydata-profiling.ydata.ai/docs/master/pages/advanced_usage/corr_mat_access.html 
the expected output is as follows:

dict_keys(['auto', 'spearman', 'pearson', 'kendall', 'cramers', 'phi_k'])

### Data Description

My data is publicly available from https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

### Code that reproduces the bug

```Python
# Computing the report
data = pd.read_csv(
    "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
)
profile = ProfileReport(data, title="Titanic")

# Listing available correlation
correlations = profile.description_set["correlations"]
print(correlations.keys())
```

### pandas-profiling version

v3.6.3

### Dependencies

```Text
pandas==1.4.4
numpy==1.21.5
```

### OS

Windows 11

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by aquemy** [comment]
I think this is due to the fact that we now only compute the `auto` correlation by default and thus, return only these coefficients.

It might be rather something to update in the documentation rather than a bug in the code.

@fabclmnt FYI

**Comment by kaijensen1** [comment]
@aquemy thank you for replying to my report! Could you let me know what parameter I need to alter to generate the other coefficients? Or point to where in the docs I could find that info?

Thanks!

**Comment by aquemy** [comment]
@kianmeng you can find all the different possible values for the setting in the documentation here: https://ydata-profiling.ydata.ai/docs/master/pages/advanced_usage/available_settings.html#correlations

Here is the doc on how to change the settings: https://ydata-profiling.ydata.ai/docs/master/pages/advanced_usage/changing_settings.html

And for your particular example, this should work:
```python
# Computing the report
data = pd.read_csv(
    "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
)
profile = ProfileReport(data, title="Titanic", correlations={
        "auto": {"calculate": True},
        "pearson": {"calculate": True},
        "spearman": {"calculate": True},
        "kendall": {"calculate": True},
        "phi_k": {"calculate": True},
        "cramers": {"calculate": True},
    },)
```

**Comment by kaijensen1** [comment]
Thank you!

**Comment by kianmeng** [comment]
@aquemy I think you're tagging the wrong person?

**Comment by Siddhartha-Mahajan** [comment]
> @aquemy  @kaijensen1  you can find all the different possible values for the setting in the documentation here: https://ydata-profiling.ydata.ai/docs/master/pages/advanced_usage/available_settings.html#correlations
> 
> Here is the doc on how to change the settings: https://ydata-profiling.ydata.ai/docs/master/pages/advanced_usage/changing_settings.html
> 
> And for your particular example, this should work:
> 
> ```python
> # Computing the report
> data = pd.read_csv(
>     "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
> )
> profile = ProfileReport(data, title="Titanic", correlations={
>         "auto": {"calculate": True},
>         "pearson": {"calculate": True},
>         "spearman": {"calculate": True},
>         "kendall": {"calculate": True},
>         "phi_k": {"calculate": True},
>         "cramers": {"calculate": True},
>     })
> ```
I was using the same for a different dataset and for some reason "cramers" doesn't show up in the profile report? it doesnt show correlation at all if only cramers calculate is set to true. 
this was the code snippet i'm using: 
```python
# Generate the Profiling Report
profile = ProfileReport(df1, title="lini_biochemical10", html={"style": {"full_width": True}}, sort=None,correlations={
            "auto": {"calculate": False},
            "pearson": {"calculate": False},
            "spearman": {"calculate": False},
            "kendall": {"calculate": False},
            "phi_k": {"calculate": False},
            "cramers": {"calculate": True},
        })
```
