### ISSUE TITLE
Feature Request: install via conda-forge

### ISSUE THREAD

**Issue by JovanVeljanoski** [ydataai/ydata-profiling#1263]
### Missing functionality

In the previous iterations, `pandas-profiling` was available via conda-forge.  I am wondering if it would be possible to make the new version now called `ydata-profiling` also available there. Thanks!

### Proposed feature

Make `ydata-profiling` available via conda-forge.

### Alternatives considered

Keep using older versions.

**Comment by fabclmnt** [comment]
Hi @JovanVeljanoski , 

thank you for your suggestion! Indeed conda-forge is missing for ydata-profiling. We will prioritize this request!

**Comment by fabclmnt** [comment]
It is now available :) 

https://anaconda.org/conda-forge/ydata-profiling
