### ISSUE TITLE
Feature request: Add sample head and tail to minimal setting

### ISSUE THREAD

**Issue by monyoudom** [ydataai/ydata-profiling#1264]
### Missing functionality

It would be good If we provide sample head and tail with minimal True. 

### Proposed feature

With minimal True we still able to see the head and tail of data,

**Comment by fabclmnt** [comment]
Hi @monyoudom ,

thank you for your feature request. We will take it into consideration.

In the meantime, can I suggest you combine the minimal setting with the sample configuration? You can even create your config file and use it as input to your ProfileReport. 

`from ydata_profiling import ProfileReport

report = ProfileReport(df, minimal=True, samples={'head':10, 'tail':10}`

Attached is the configuration file, assuming 10 sample rows. You adapt the number of rows to your needs. 
config_minimal_sample.yaml

Let me know how it went.

**Comment by monyoudom** [comment]
Thanks it does help a lot.
