### ISSUE TITLE
Feature Request: update ALERTS section from JSON output to be as complete as the HTML output

### ISSUE THREAD

**Issue by Robin66014** [ydataai/ydata-profiling#1301]
### Missing functionality

The ALERTS section from the to_json() output gives only the types of errors and the column name (e.g. HIGH_CORRELATION, or ZEROS), but for example for the HIGH_CORRELATION error doesn't tell with which columns it is highly correlated to (although for this one specific I can obtain it from a different section of the JSON output). For the ZEROS warning the json output says '[ZEROS] alert on column XLarge Bags', but doesnt supply the information that it has 704 zero's (while the HTML output does actually show this). See the two images below to display the output difference:
![image](https://user-images.githubusercontent.com/74533268/228914784-7dec95af-fdce-4fab-803d-27efcdc37f82.png)
![image](https://user-images.githubusercontent.com/74533268/228914812-8b41a489-2680-4783-8bf7-3f201673efdf.png)

### Proposed feature

A more extensive JSON output from the to_json() function. The ALERTS section should not only tell what alert/error was encountered, but also quantify the errors (e.g. not only display [ZEROS] alert in column X, but just as in the HTML output format: [ZEROS] there were 704 zero's encountered in column X.

### Alternatives considered

in the rest of the JSON string output details about the correlations can be obtained, but for the missing values (ZEROS), this is not possible as the JSON output is a barchart written out in HTML info.

### Additional context

shouldn't be too difficult to fix, as the information exists in the HTML report, but not in the to_json() JSON string

**Comment by fabclmnt** [comment]
Hi @Robin66014,
thank you for the detailed request! Indeed this is something that can improve the experience with the _to_json_ method.

I've added to YData Profiling Roadmap - https://github.com/orgs/ydataai/projects/16

**Comment by haq9966** [comment]
Hi,
In alert which have multiple high levels of correlations, the json file simply says the total number of high levels of correlation. Whereas in the HTML, it is possible to see what these are by simply hovering over them. Is it possible to replicate this using json alone?
