### ISSUE TITLE
Using tsmode=True, check if data.index is a DateTime index, if so include it in the analysis

### ISSUE THREAD

**Issue by CatChenal** [ydataai/ydata-profiling#1316]
### Missing functionality

I've used ProfileReport with tsmode=True on a pd.DataFrame indexed with a DateTime index. My assumption was that the report would provide some basic analysis on that index as well as on the values. The report indicates the number of missing values in all columns, which is great, but I could find no analysis on the index. 

Namely, what I was expecting, specifically because my index has the 'right' type (unlike the case in #1292 as I understand it), is the following:
1. Detection of the frequency in the index time series
2. Detection of gaps in the index time series

### Proposed feature

When the data passed to ProfieReport with tsmode=True and the data is DateTime indexed, analyze the index for:
1. Detection of the frequency in the index time series
2. Detection of gaps in the index time series

### Alternatives considered

Possible implementation:

Add an `index=true` (default is false) item under the `vars` section of the default.yml file, this would entail the following:
```
# pseudocode:

if index:
    data.reset_index(names='index')     # or index_series = data.index.to_series()
    check_freq(data.index) 
    check_gaps(data.index)
    data.set_index('index')
[...proceed with current analysis]
```

### Additional context

In the case of time series, the data values could have 0 missing values, yet there could be gaps in their associated time series (my case).

**Comment by fabclmnt** [comment]
Hey @CatChenal ,

thank you for your suggestion. This is indeed a great request for time-series functionality.
We have included it into our roadmap.

**Comment by alexbarros** [comment]
added in https://github.com/ydataai/ydata-profiling/pull/1399 and https://github.com/ydataai/ydata-profiling/pull/1410

**Comment by CatChenal** [comment]
Thanks!
