### ISSUE TITLE
Request: Include non-null count in summary statistics for variable

### ISSUE THREAD

**Issue by gdevenyi** [ydataai/ydata-profiling#1334]
### Missing functionality

A count of non-null values

### Proposed feature

Currently, percent missing is provided as part of the summary, but I'd really appreciate an exact count somewhere.

**Comment by aquemy** [comment]
@gdevenyi I believe that the count is available just above the %, or am I missing something?

**Comment by gdevenyi** [comment]
Right, I see there's a "Missing cells" number. I don't know how I missed it.

Complimentary to this however, there's no "total cells" number..
