### ISSUE TITLE
Reproduction tab doesn't correctly indicate version used

### ISSUE THREAD

**Issue by gdevenyi** [ydataai/ydata-profiling#1335]
### Current Behaviour

![image](https://github.com/ydataai/ydata-profiling/assets/3001850/3c499a9c-a07c-44c1-b905-959cff90be11)

### Expected Behaviour

Version reported as 4.1.2, the version used.

### Data Description

N/A

### pandas-profiling version

v4.1.2

### Dependencies

```Text
N/A
```

### OS

Linux

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @gdevenyi ,

although there is small typo (double v), the version of the package is being correctly generated as per the image below:
![image](https://github.com/ydataai/ydata-profiling/assets/30911746/64d017f7-674a-4ff9-8b7e-9dfc83a30128)

Can you please make sure you are installing the latest packages version either through pypi or conda?

**Comment by fabclmnt** [comment]
I'll be closing this issue as it is not possible to reproduce.
