### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by jashbycu** [ydataai/ydata-profiling#1344]
### Current Behaviour

When I install this with pip alongside requests==2.31.0 (which is required to satisfy https://github.com/advisories/GHSA-j8r2-6x86-q33q ), I get `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.1.2 requires requests<2.29,>=2.24.0, but you have requests 2.31.0 which is incompatible.`

### Expected Behaviour

ydata-profiling should be compatible with requests==2.31.0. This repo's requirements.txt file suggests this should be the case, so I'm not exactly sure why pip requires requests<2.29. Maybe there is another package used by ydata-profiling that is imposing this restriction?

### Data Description

n/a

### pandas-profiling version

v4.1.2

### Dependencies

```Text
requests==2.31.0
```

### OS

macos and debian

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @jashbycu ,

thank you for your request!

This issue is closed by  https://github.com/ydataai/ydata-profiling/pull/1326.
