### ISSUE TITLE
'config_explorative.yaml' NOT FOUND

### ISSUE THREAD

**Issue by SamuelDevdas** [ydataai/ydata-profiling#1358]
### Current Behaviour

![image](https://github.com/ydataai/ydata-profiling/assets/84823680/68e35c96-aa6e-4a16-85a4-a223812beafb)

### Expected Behaviour

file should display

### Data Description

file should display

### pandas-profiling version

NA

### Dependencies

```Text
NA
```

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @SamuelDevdas,

this file was deleted long ago as the definition of the explorative mode have changed.

Now you can find it defined here: https://github.com/ydataai/ydata-profiling/blob/def4cfa47d071b20a73ae63fa54f2039968eed78/src/ydata_profiling/config.py#L428

You are still able to create your own _config_explorative.yaml_ file, but for the package default when explorative=True is no longer required.
