### ISSUE TITLE
Time series mode inactive

### ISSUE THREAD

**Issue by xshi19** [ydataai/ydata-profiling#1359]
### Current Behaviour

The following code produces a regular report instead of a time series report as shown in https://ydata.ai/resources/how-to-do-an-eda-for-time-series.
```
from pandas_profiling import ProfileReport
profile = ProfileReport(df, tsmode=True, sortby="datadate", title="Time-Series EDA")
profile.to_file("report_timeseries.html")
```
In addition the time series example [USA Air Quality](https://github.com/ydataai/ydata-profiling/tree/master/examples/usaairquality)) (Time-series air quality dataset EDA example) cannot be found in the git repository. 

### Expected Behaviour

A time series report as in https://ydata.ai/resources/how-to-do-an-eda-for-time-series

### Data Description

My dataframe has only two columns "datadate" (pandas datetime) and "value" (float). 

### pandas-profiling version

v4.2.0

### Dependencies

```Text
python==3.7.1
numpy==1.21.5
pandas==1.3.5
```

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @xshi19,

can you please share what is the dataset that you are using? The time-series report is generated when ts_mode set to true the variables are only identified as time-series if they do have a certain level of auto-correlation[ as per in the documentation.](https://ydata-profiling.ydata.ai/docs/master/pages/use_cases/time_series_datasets.html#time-series-data) 

It is not a good practice to have datasets being stored in Github. For that reason we use our **cache_file** method to download the data from an URL (code snippet from the python example): 

`
from ydata_profiling import ProfileReport
from ydata_profiling.utils.cache import cache_file
from ydata_profiling.visualisation.plot import timeseries_heatmap

if __name__ == "__main__":

    file_name = cache_file(
        "pollution_us_2000_2016.csv",
        "https://query.data.world/s/mz5ot3l4zrgvldncfgxu34nda45kvb",
    )`

I have just tested the code and the dataset is being downloaded as expected. 
Let me know if I can further help you with your data.

**Comment by fabclmnt** [comment]
Hi @xshi19 ,

can you please confirm if this was enough to solve your issue?

I'll close the issue, but happy to have it re-open in case this wasn't helpful.
