### ISSUE TITLE
For continuous-categorical relationships, why was discretizing continuous features chosen over using Kruskal?

### ISSUE THREAD

**Issue by kylegilde** [ydataai/ydata-profiling#1372]
I feel like using the Kruskal test would be more reliable as opposed to choosing an arbitrary number of bins for discretization.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kruskal.html#scipy.stats.kruskal

The Kruskal-Wallis H-test tests the null hypothesis that the population median of all of the groups are equal. It is a non-parametric version of ANOVA. The test works on 2 or more independent samples, which may have different sizes. Note that rejecting the null hypothesis does not indicate which of the groups differs. Post hoc comparisons between groups are required to determine which groups are different.

https://github.com/ydataai/ydata-profiling/blob/cfb020d9ad0ce7ef3be53962763b7a57b88732f9/src/ydata_profiling/model/pandas/correlations_pandas.py#L183-L185

**Comment by aquemy** [comment]
Hi @kylegilde ,

I am not sure to understand what you propose, so let me summarize what we are doing here.

The `auto` correlation matrix aims at computing pairwise correlation between **all** columns regardless of their data type and semantic.
For instance, Pearson cannot be use between categorical variables. We could use plenty of different associations measures altogether depending on very specific cases, but this would hurt the interpretability of the final matrix. For this reason, we have chosen to minimize the number of associations metrics an use the ones already available within `ydata-profiling`: Pearson for numerical to numerical, Cramers'V for categorical to categorical.

The remaining problem was numerical to categorical. There are few association metrics to handle such cases, but none of them are very popular and thus, would not necessarily be a good metric for our user base.
Instead, we have chosen to discretize the numerical variable to turn the numerical to categorical into a categorical to categorical. The discretization needs to be rather fast, so uniform or quantile based.


As I said, I am not exactly sure what your propose but Kruskal is a frequentist test that by construction does not measure the association between variables. For the correlation matrix, we need a measure that we can normalize between [0,1] and preferably with a linear interpretation.

Can you let us know a bit more what you have in mind? Maybe this is something that can be useful somewhere else than the correlation matrix.

**Comment by kylegilde** [comment]
Yes, I see your point about Kruskal and why that doesn't work.

From the [docs](https://ydata-profiling.ydata.ai/docs/master/pages/reference/api/_autosummary/ydata_profiling.config.Settings.html), it looks like the default n_bins for Cramer's V is 10.

I'm curious if there is a rationale for using 10.

**Comment by fabclmnt** [comment]
Hi @kylegilde the number of bins is a configurable input. Depending on your dataset you might want to tune it.

**Comment by kylegilde** [comment]
Sounds good, thank you
