### ISSUE TITLE
Bug Report: ProfileReport fails if column has only empty strings

### ISSUE THREAD

**Issue by BraginIvan** [ydataai/ydata-profiling#1373]
### Current Behaviour

```
    profile = ProfileReport(
        pd.DataFrame({
            "q": ["", None, " "],
            "v": [1, 2, 3]
        }),
        minimal=True,
    ).html
```
Fails with 

```
    wordcloud = WordCloud(
  File "/wordcloud/wordcloud.py", line 410, in generate_from_frequencies
    raise ValueError("We need at least 1 word to plot a word cloud, "
ValueError: We need at least 1 word to plot a word cloud, got 0.
```

### Expected Behaviour

Should create an html

### Data Description

one of df columns should have only empty strings and Nones

### Code that reproduces the bug

```Python
import pandas as pd 
from ydata_profiling import ProfileReport
profile = ProfileReport(
        pd.DataFrame({
            "q": ["", None, " "],
            "v": [1, 2, 3]
        }),
        minimal=True,
).html
```

### pandas-profiling version

v4.3.1

### Dependencies

```Text
pandas=1.5.3
```

### OS

MacOs 13.4 (22F66)

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

Hints

        pd.DataFrame({
            "q": ["", None, " "],
            "v": [1, 2, 3]
        })
- q type is Text in the df ^
- text summarizer culculates word_counts but remove whitespaces. So we have empry series
ydata_profiling.model.pandas.describe_categorical_pandas.word_summary_vc
words = word_lists.explode().str.strip(string.punctuation + string.whitespace)
- wordcloud cant work with empty series
wordcloud.wordcloud.WordCloud.generate_from_frequencies
        if len(frequencies) <= 0:
            raise ValueError("We need at least 1 word to plot a word cloud, "
                             "got %d." % len(frequencies))
- As I understood in the previous versions q would be categorical not Text

**Comment by Ge0f3** [comment]
Any update on this or a solution to bypass this?

**Comment by alexbarros** [comment]
> Any update on this or a solution to bypass this?

Not yet, but you can bypass this by setting the variable as categorical using type_schema:
```python
import pandas as pd 
from ydata_profiling import ProfileReport
profile = ProfileReport(
        pd.DataFrame({
            "q": ["", None, " "],
            "v": [1, 2, 3]
        }),
        minimal=True,
        type_schema={"q": "categorical"},
).html
```
