### ISSUE TITLE
feat: Put date tick label in Profiling Report UI

### ISSUE THREAD

**Issue by sndpgm** [ydataai/ydata-profiling#1375]
Hello, development teams!
Thank you very much for maintaining this useful library!

Now  I use Profile Report UI for visualizing time series data, and want to put date tick label in a graph instead of integer series.
![image](https://github.com/ydataai/ydata-profiling/assets/108000555/63bb998a-e5eb-4bb1-a9d0-ef2e5d9ca3b3)

Does `ydata_profiling.ProfileReport` support setting date label in time series graphs?

**Comment by fabclmnt** [comment]
Hi @sndpgm,

this is currently under development and expected to be included in the next package release.

**Comment by alexbarros** [comment]
added in https://github.com/ydataai/ydata-profiling/pull/1399
