### ISSUE TITLE
Further analysis

### ISSUE THREAD

**Issue by Fatemeh490** [ydataai/ydata-profiling#1376]
### Current Behaviour

say that I think the data type detected by ydata-profiling is what I want. So if I want to do more analysis on these data how can I access each variables? 

### Expected Behaviour

I want to use other kind of visualization like box plot or scatter plot and so on. So I need that detected data type. 

### Data Description

I an using Titanic dataset.

### pandas-profiling version

v4.2.0

### Dependencies

```Text
pandas==1.5.3
```

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @Fatemeh490, 

thank you for your question. All the information available through the ydata-profiling report can be easily accessed through json. 

Please see the code example below: 

`from json import loads
from ydata_profiling import ProfileReport

profile = ProfileReport(
        group[1],
        tsmode=True,
        sortby="Date Local",
        # title=f"Air Quality profiling - Site Num: {group[0]}"
    )

report_json = loads(profile.to_json())

#Get the statistics per variable
variables_info = report_json['variables']`

**Comment by Fatemeh490** [comment]
Great! That was what I wanted. Tnx
