### ISSUE TITLE
Bug Report: Unable to install this package

### ISSUE THREAD

**Issue by vsiddharth365** [ydataai/ydata-profiling#1385]
### Current Behaviour

On installing it gives an error:
match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
in file: venv/Lib/site-packages/pip/_vendor/packaging/version.py
When I modified this file by specifying version of pip on my system as an string, it got installed but then threw new errors. Here's the change I did:
`    
          def __init__(self, version: str) -> None:
                  # Validate the version and parse it into pieces
                  version = "22.3.1"         ######################################### here
                  match = self._regex.search(version)
                  if not match:
                      raise InvalidVersion(f"Invalid version: '{version}'")

        # Store the parsed out pieces of the version
        self._version = _Version(
            epoch=int(match.group("epoch")) if match.group("epoch") else 0,
            release=tuple(int(i) for i in match.group("release").split(".")),
            pre=_parse_letter_version(match.group("pre_l"), match.group("pre_n")),
            post=_parse_letter_version(
                match.group("post_l"), match.group("post_n1") or match.group("post_n2")
            ),
            dev=_parse_letter_version(match.group("dev_l"), match.group("dev_n")),
            local=_parse_local_version(match.group("local")),
        )

        # Generate a key which will be used for sorting
        self._key = _cmpkey(
            self._version.epoch,
            self._version.release,
            self._version.pre,
            self._version.post,
            self._version.dev,
            self._version.local,
        )
`

The new error is:
ImportError: cannot import name 'prod' from 'scipy._lib._util' (\venv\Lib\site-packages\scipy\_lib\_util.py)

### Expected Behaviour

The package should get installed without errors and work properly post that.

### Data Description

The dataset I am using is available at: https://www.kaggle.com/datasets/mnassrib/jena-climate
I want to do EDA of this data.

### Code that reproduces the bug

```Python
Here's the code I am using this package in:
`
        from ydata_profiling import ProfileReport
        profile = ProfileReport(df)
        profile.to_file("output.html")
`
```

### pandas-profiling version

4.3.1
Python interpreter = Python 3.11.3

### Dependencies

```Text
pandas==2.0.3
numpy==1.23.5
scipy==1.10.1
scikit-learn==1.3.0
pip==22.3.1
```

### OS

Windows 11

### Checklist

- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by vsiddharth365** [comment]
The second error: ImportError: cannot import name 'prod' from 'scipy._lib._util' (\venv\Lib\site-packages\scipy_lib_util.py) got resolved on reinstalling scipy package.

**Comment by vsiddharth365** [comment]
The package installs normally after changing some network permissions.

**Comment by Nirmalvani** [comment]
ImportError: cannot import name 'DataError' from 'pandas.core.base' (C:\Users\Admin\anaconda3\Lib\site-packages\pandas\core\base.py)

Bro i am getting error like this tried all the possible outcome but it has not been solved yet. plz help me to resolve this issue.
