### ISSUE TITLE
Mamba installation requiring downgrading pandas version

### ISSUE THREAD

**Issue by jbwhit** [ydataai/ydata-profiling#1436]
### Current Behaviour

I'm not sure if this is a `ydata-profiling` bug or a mamba/conda problem. I have `conda-forge` as a channel. When I try to install with the command: `mamba install ydata-profiling` I get the following output: 

```bash
...
  Package            Version  Build            Channel           Size
───────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────

  + wordcloud          1.9.2  py310h6729b98_1  conda-forge      163kB
  + phik              0.12.3  py310ha51cec0_0  conda-forge     Cached
  + dacite             1.8.0  pyhd8ed1ab_0     conda-forge     Cached
  + visions            0.7.5  pyhd8ed1ab_0     conda-forge     Cached
  + ydata-profiling    4.5.1  pyhd8ed1ab_1     conda-forge      203kB

  Downgrade:
───────────────────────────────────────────────────────────────────────

  - pandas             2.1.0  py310h5262a37_0  conda-forge     Cached
  + pandas             2.0.3  py310h5e4fcda_1  conda-forge       12MB

  Summary:

  Install: 5 packages
  Downgrade: 1 packages
```

Where it's finding the current version of `ydata-profiling` but it's requiring `pandas` to downgrade from the current version 2.1.0 to 2.0.3. 

### Expected Behaviour

Expected behavior would be to simply install `ydata-profiling` without downgrading the `pandas` installation. I saw previous bugs where conda / mamba was trying to install an old version of `ydata-profiling` but this is the first that I've seen that's asking for `pandas` to be downgraded.

### Data Description

N/A

### pandas-profiling version

v4.5.1

### Dependencies

```Text
pandas==2.1.0
python==3.10
```

### OS

MacOS

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @jbwhit ,

because pandas 2.1.0 is introducing some breaking changes, in ydata-profiling we have kept the pandas version bounded to versions that are below to 2.1.0 as per [our setup file](https://github.com/ydataai/ydata-profiling/blob/develop/requirements.txt).

How relevant is for you to be using pandas 2.1.0? Can you please share a bit more on your experience? 

I'll keep this request open so it can be upvoted by the community!

**Comment by jbwhit** [comment]
We can close this. I just tested this with the newest pandas release v2.2.0 and it looks to work without requiring a downgrade. It does seem to require numpy to be downgraded, but that's another for another issue. 

```
  - numpy                    1.26.3  py310h4bfa8fc_0    conda-forge
  + numpy                    1.25.2  py310h7451ae0_0    conda-forge/osx-64     Cached
```
