### ISSUE TITLE
[BUG] 🐛 `TypeCheckError` thrown when initialising a report

### ISSUE THREAD

**Issue by chrimaho** [ydataai/ydata-profiling#1439]
### Current Behaviour

Error thrown when initialising a report:

``` txt
TypeCheckError: argument "config_file" (None) did not match any element in the union:
  pathlib.Path: is not an instance of pathlib.Path
  str: is not an instance of str
```

### Expected Behaviour

No error to be thrown.

### Data Description

Happens on all data.

### Code that reproduces the bug

```Python
from ydata_profiling import ProfileReport
from pycaret.datasets import get_data
data = get_data(dataset="germany", verbose=False)
ProfileReport(data, title="Pandas DataFrame")
```

### pandas-profiling version

v4.5.1

### Dependencies

```Text
pandas
numpy
pycaret
```

### OS

Ubuntu

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by 2spring** [comment]
Hello , I am getting the same error , with the following code as Notebook (Jupyter Lab): 

```
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing(as_frame = True)
df = housing.frame
df.head()  # Dataframe shows up correctly

from ydata_profiling import ProfileReport   #No import Error
profile = ProfileReport(df, title="Profiling Report")  #Runnning this Cell Throws the same error : 
```


```
--> 408 raise TypeCheckError(f"did not match any element in the union:\n{formatted_errors}")

TypeCheckError: argument "config_file" (None) did not match any element in the union:
  pathlib.Path: is not an instance of pathlib.Path
  str: is not an instance of str
```

Version , Anaconda Distribution on Windows 10 x64  : `ydata-profiling           4.5.1              pyhd8ed1ab_1    conda-forge`

Thank you in advance .

**Comment by aquemy** [comment]
It looks like a type checking issue that was unnoticed before the upgrade to Pydantic.

We'll solve that shortly.

**Comment by bdeck8317** [comment]
> It looks like a type checking issue that was unnoticed before the upgrade to Pydantic.
> 
> We'll solve that shortly.

Any movement on this issue?
