### ISSUE TITLE
html out of memory

### ISSUE THREAD

**Issue by levisocool** [ydataai/ydata-profiling#1441]
### Current Behaviour

First, thanks for developing a wonderful tool!
My problem is the memory problem when opening .html file created by “profile.to_file("your_report.html")”. By the way, my dataset is stored in csv with 700k+ rows and 40+ columns. The suggestions online said "increasing the virtual memory" but i could't do that.
Is there any solutions or suggestions for problem? Hope to get some help. Thanks again.

### Expected Behaviour

Want to browse the profile results.

### Data Description

my dataset is stored in csv with 700k+ rows and 40+ columns. All data types are  float.

### pandas-profiling version

v4.5.1

### Dependencies

```Text
..
```

### OS

Windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @levisocool ,

You have achieved a browser memory limit and for that reason the report won't render. It is a limitation for the open-source version of the package. However this is a limitation that can be overcome with the navigation experience that we provide with our`[ community version of YData Fabric](https://ydata.ai/ydata-fabric-free-trial)`. 

There are ways to mitigate this in the OSS, but for all the options there is a loss of information. For eg. [use the explorative report instead](https://docs.profiling.ydata.ai/4.5/getting-started/quickstart/#deeper-profiling), that only computes the univariate metrics.
