### ISSUE TITLE
AttritubeError mplDeprecation with matplotlib 3.8.0

### ISSUE THREAD

**Issue by erreurBarbare** [ydataai/ydata-profiling#1455]
### Current Behaviour

The following error occurs, when running a project with matplotlib 3.8.0

```
warnings.filterwarnings("ignore", category=matplotlib.cbook.mplDeprecation)
AttributeError: module 'matplotlib.cbook' has no attribute 'mplDeprecation'
```

Reported here as well: https://stackoverflow.com/questions/77128061/ydata-profiling-profilereport-attributeerror-module-matplotlib-cbook-has-no

### Expected Behaviour

No error. Possibility to use matplotlib 3.8.0

### Data Description

-

### Code that reproduces the bug

```Python
Problem seems to come from here: https://github.com/ydataai/ydata-profiling/blob/develop/src/ydata_profiling/visualisation/context.py#L85
```

### pandas-profiling version

-

### Dependencies

```Text
-
```

### OS

Manjaro / Docker python:3.11-slim 

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by garciadias** [comment]
Got the same error. Changed to matplotlib 3.7.3, the newest version before 3.8 and it worked.

**Comment by a-chumagin** [comment]
Looks like it will be fixed in the next release 
https://github.com/ydataai/ydata-profiling/blob/develop/requirements.txt#L3

**Comment by melanopsis** [comment]
Can someone please re-open this? Pinning a dependency to its earlier version to prevent an issue is not really a resolution but a temporary workaround.
