### ISSUE TITLE
Allow Typeguard >=3

### ISSUE THREAD

**Issue by CleKrausFlex** [ydataai/ydata-profiling#1472]
### Missing functionality

ydata-profiling still depends on relatively old version of typeguard (typeguard>=2.13.2, <3) which leads to conflicts with other packages. Is there any chance it could be updated?

### Proposed feature

Update typeguard version

**Comment by aquemy** [comment]
@CleKrausFlex the PR allowing up to the next major version (v5) has been merged already.
It was release with the last version of `ydata-profliing` (v4.6.0): https://github.com/ydataai/ydata-profiling/blob/master/requirements.txt#L23
