### ISSUE TITLE
PydanticImportError ❌

### ISSUE THREAD

**Issue by triposat** [ydataai/ydata-profiling#1505]
I am using Python 3.9 and trying to install the `pandas-profiling` but am facing issues while importing the `pandas-profiling` module. The module is successfully installed but when I am importing I am facing the below error:

<img width="823" alt="Screenshot 2023-11-16 111241" src="https://github.com/ydataai/ydata-profiling/assets/69134468/234a85a1-fcde-4fc0-ba2a-bcb08a5d27de">
<img width="830" alt="Screenshot 2023-11-16 111254" src="https://github.com/ydataai/ydata-profiling/assets/69134468/5c5a2f6e-47ba-4ac3-b280-3646a667396b">

**Comment by chengaled** [comment]
Facing the same issue. Can anyone suggest a fix?

**Comment by triposat** [comment]
> Facing the same issue. Can anyone suggest a fix?

I got the solution. Actually, the pandas-profiling name has been changed. Start using ydata-profiling from now. Read more about this change here: https://pypi.org/project/pandas-profiling/

**Comment by fabclmnt** [comment]
Hi @triposat ,

thank you for your question. Indeed `pandas-profiling` have been renamed to `ydata-profiling`. New versions can be installed with `pip install ydata-profiling.`

I'll close this issue for now as I've seen that you were able to have it solved. 

Let me know if there are any other questions.
