### ISSUE TITLE
Support pandas 2.1

### ISSUE THREAD

**Issue by celestinoxp** [ydataai/ydata-profiling#1511]
### Missing functionality

.

### Proposed feature

support pandas 2.1

### Additional context

I'm working on a pull-request so that the PyCaret package can support pandas 2.1.
It turns out that it is not possible because through third-party packages, ydata-profiling is also installed. So since ydata-profiling doesn't yet support pandas 2.1, pycaret can't either.
If possible, can you give me an upcoming date for supporting pandas 2.1? Thanks

**Comment by fabclmnt** [comment]
Hi @celestinoxp,

most probably in the beginning of January. As you can see in the PR list, the PR is open, but there are several conflicts that need to be solved in the meantime. Feel free to contribute!

**Comment by aquemy** [comment]
The main issue with the PR from Renovate is that it tries to also update Spark which will not work.
I created a separated PR to update only the non-Spark requirements.  
https://github.com/ydataai/ydata-profiling/pull/1512
