### ISSUE TITLE
No module named 'ydata_profiling'

### ISSUE THREAD

**Issue by makgul1** [ydataai/ydata-profiling#1530]
### Current Behaviour

after installing ydata using the following command

conda install -c conda-forge ydata-profiling

I can use

from ydata_profiling import ProfileReport

in the python cmd window. However, in the jupyter notebook I get the 

following error:

ModuleNotFoundError: No module named 'ydata_profiling'

### Expected Behaviour

the import 

from ydata_profiling import ProfileReport

in jupyter notebook should work

### Data Description

NA

### Code that reproduces the bug

```Python
from ydata_profiling import ProfileReport
```

### pandas-profiling version

ydata-profiling           4.1.1 

### Dependencies

```Text
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.3.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.3.1                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-lsp               2.2.0                    pypi_0    pypi
jupyter-server            2.7.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.0.3                    pypi_0    pypi

ydata-profiling           4.1.1            py38haa95532_0
```

### OS

windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @makgul1 
make sure that you are using this package: https://anaconda.org/conda-forge/ydata-profiling

`conda install main::ydata-profiling`

We have no control on Anaconda distributions, and unfortunately there is a replicated repo (by another entity) that does not work properly .

**Comment by simonespa** [comment]
hi @fabclmnt, can this package be installed with `pip` too?

I'm using `pip` and up until `ydata-profiling` version `4.7.0`, I could do 

```python
from ydata_profiling import ProfileReport

# Load the data
df = pd.read_csv("some_data.csv")

# Produce and save the profiling report
profile = ProfileReport(df, title="Some Data Profile Report")
profile.to_file("report.html")
```
and it was working fine. Now that I've updated to version `4.8.3` I get `ModuleNotFoundError: No module named 'ydata_profiling'`

I'm running on
- Python 3.11.7
- notebook==7.2.0
- jupyterlab==4.2.0

**Comment by fabclmnt** [comment]
Yes,  the package can be installed with `pip`. 

I'll need more detail given that the team is not being able to reproduce the error mentioned with even the latest versions of the package - (https://pypi.org/project/ydata-profiling/).

Screenshots below: 
![image](https://github.com/ydataai/ydata-profiling/assets/30911746/881d0589-c063-4950-a479-20a77fe24a99)

![image](https://github.com/ydataai/ydata-profiling/assets/30911746/b3be9af9-8e20-475d-8dda-2d1c13825bb2)

**Comment by Diego-Oliveiras** [comment]
I had this same problem, I installed the libraries: 

pip install ipywidgets
pip install ipython
pip install configuration tools

it will probably work
