### ISSUE TITLE
Report is too large for any browser to render

### ISSUE THREAD

**Issue by kstech-roadie** [ydataai/ydata-profiling#1579]
### Current Behaviour

After running the profiler on ~41k records with maybe 100 or so fields, it produces an HTML report so large that no browser can render it.  There was no error, and all the data is there, and all the SVGs are produced. Its just that the report tries to render as a _single page_.  Tested with Chrome, Firefox, Brave, Edge and a couple others. They all crash because they're trying to render something like 80Mb of HTML and SVG.  I would recommend breaking up the single page report into many documents that can be linked together, more like a website.  Or some other technique other than shoving 80Mb into a single page.  It doesnt work.

### Expected Behaviour

the report is viewable

### Data Description

41k records X 100 fields

### pandas-profiling version

4.7.0

### Dependencies

```Text
pandas==2.2.1
```

### OS

macos and linux

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @kstech-roadie ,

thank you for opening the issue. As you can imagine the generation of a static report using HTML does have its own limitations, being one of them the amount of data and variables that can be handled through your browser. 

If you want to leverage a  dashboard experience that allows you to navigate bigger volumes of data, you need a different type of infrastructure and logic to support it. Give a go to[ YData Fabric](https://ydata.ai/register) where you can find that experience.
