### ISSUE TITLE
request for consistent tag formatting

### ISSUE THREAD

**Issue by hubutui** [ydataai/ydata-profiling#1591]
### Current Behaviour

When you publish new versions or create new tags for this repository, could you please adhere to a consistent format? something like vx.y.z is fine. This would help me a lot. Thank you.

### Expected Behaviour

tag looks like vx.y.z, eg. v4.8.3

### Data Description

none

### pandas-profiling version

4.8.3

### Dependencies

```Text
none
```

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
@hubutui we do have a consistent tagging system, not sure what do you mean by that . We do keep the same format 4.*.*
This last release there was an issue with the actions and that triggered some issues regarding the pre-release versions, but not the published version itself. This is something we can control. 

But perhaps you could detail a bit more and be more specific? As we might be missing your point.

**Comment by hubutui** [comment]
Yes, I found the release v4.8.3, https://github.com/ydataai/ydata-profiling/releases/tag/4.8.3,  but the tag is 4.8.3. So the source tarball url is https://github.com/ydataai/ydata-profiling/archive/refs/tags/4.8.3.tar.gz. But the previous release and git tags, they're something like v4.8.1, with source tarball https://github.com/ydataai/ydata-profiling/archive/refs/tags/v4.8.1.tar.gz. Note the prefix `v` in both the tag name and source tarball url. Just make it consistent, always with or without the `v` prefix. This is very helpful for me to automatically download the new source tarbal once a new release is available with a robot checking the new release with github api.

**Comment by fabclmnt** [comment]
As mentioned previously, that release was an outlier as we had issues with the system and release process. 

Rest assured we have and we have always had the tag formatting in place for the releases.
