### ISSUE TITLE
Word Cloud for categorical is not nice

### ISSUE THREAD

**Issue by Sweetea99** [ydataai/ydata-profiling#1615]
### Missing functionality

I like the original bar chart for categorical cols now it comes as a word cloud . 

### Proposed feature

is there a way to get back to bar chart?

### Alternatives considered

I like original better

**Comment by fabclmnt** [comment]
Hi @Sweetea99 ,

the barplot is what is used for categorical cols. Word cloud is used only for string type columns, as per the example below:
![image](https://github.com/ydataai/ydata-profiling/assets/30911746/ca350a73-039e-47e8-b4d1-f7e5363eb34e)

In case your columns was incorrectly identified please use the documentation example to set the correct data type: https://docs.profiling.ydata.ai/4.5/advanced_settings/available_settings/#setting-dataset-schema-type

Hope this helps.
