### ISSUE TITLE
stationarity test

### ISSUE THREAD

**Issue by Blackandwhite23** [ydataai/ydata-profiling#1639]
### Missing functionality

It would be nice if the parameters for adfuller could be configured.

### Proposed feature

If you have very large data sets, then using the standard AIC takes too much time and too much RAM.
It would be nice to chose BIC or maxlags.
e.g.
      result = adfuller(series.dropna(), autolag='BIC')
or
      result = adfuller(series.dropna(), maxlag=30)

**Comment by fabclmnt** [comment]
@alexbarros can you please add this issue to your backlog?
