### ISSUE TITLE
Feature Request: Configure which Alerts to be rejected

### ISSUE THREAD

**Issue by daso94msg** [ydataai/ydata-profiling#1642]
### Missing functionality

Right now it is possible to switch on/off the rejection of variables entirely with the configuration-variable _reject_variables_.

### Proposed feature

I would like to be able to only reject some type of variable. For example reject _missing_ variables, but still show _constant_ variables normally in the report.

### Alternatives considered

I'm not sure about a workaround, to me it seems like it depends on the Typeset as they all come back to the unsupported Basetype-

**Comment by fabclmnt** [comment]
Hi @daso94msg ,

thank you for your feature request. Nevertheless it is not totally clear what is the end goal and utility of the request. 

Can you please provide a practical example?

**Comment by daso94msg** [comment]
We use the reports to have a first glance at unknown data sets.
A column that consists only of NA-values is indeed not that interesting. 
For a constant column on the other hand, it could still be interessting to check if that constant value is plausible.
But eventually they both get grayed out in the report as rejected, which tempts you to not look into them at all.

If it's not a feature worth pursuing for you, could you give me an idea where I have to look into it?
Where does the rejection happen? I already looked in the _./ydata_profiling/model/alerts.py_ and  _./model/pandas/summary_pandas.py_ where I found out it depends on the _description["type"]_ of a series_description being "Unsupported" or not.

**Comment by fabclmnt** [comment]
I'm not sure if I followed the request. 
Constant columns in Ydata-profiling are not returned as rejected columns. They are in fact returned with a "Constant" warning as they remain the same value across the rows. 

Can you please provide a visual example with a dataset? That way we will be able to better understand the request and let you know of this is aligned with something that we would pursue.

**Comment by daso94msg** [comment]
Hi @fabclmnt,

thanks for coming back at me.
Unfortunately I can't reproduce the issue as I do not have access to the exact data that created the report in the first place, but I still have a screenshot of it:

![image](https://github.com/user-attachments/assets/601821c2-b4fa-4046-a01c-f444313a6dfc)


But I think it's not really possible to solve the problem then.

Thank you.
