### ISSUE TITLE
support for numpy >= 2.0

### ISSUE THREAD

**Issue by quant5** [ydataai/ydata-profiling#1645]
### Missing functionality

Numpy 2.0.0 was released on June 16. https://github.com/numpy/numpy/releases/tag/v2.0.0. The current version is 2.1.1.

To date, ydata-profiling is not compatible with 2.0.x per `requirements.txt`.

As such, it is currently a blocker for users to upgrade to 2.0.x if they have this package installed.

### Proposed feature

Loosen requirements to include 2.0.x unless there are specific reasons (e.g., usage of deprecated function names) not to.

**Comment by stefansimik** [comment]
This is really important. This library already forces us to downgrade to older Numpy versions and it is not very comfortable situation. Starts to be blocker for using this library.

**Comment by fabclmnt** [comment]
The development is completed and expected to be release later this week. 

https://github.com/ydataai/ydata-profiling/pull/1646

**Comment by stefansimik** [comment]
> This issue is closed since release 4.10 (Sep 7th) - https://github.com/ydataai/ydata-profiling/releases/tag/v4.10.0, where numpy has been bump.
> 
> @stefansimik which version of the package are you using?

I am using `ydata-profiling=4.10.0`.

Sending screenshot, what happened, when I installed ydata-profiling,
to show, that it somehow led to downgrade of numpy.

I installed only ydata-profiling (with ipywidgets), nothing else and this simple operation 
resulted in downgrade of Numpy.

![CleanShot 2024-10-16 at 18 32 05@2x](https://github.com/user-attachments/assets/7654301b-61de-44e1-ada5-a4a3847351d8)

**Comment by fabclmnt** [comment]
Hi @quant5,

thanks for sharing that information. The latest version of the package is now in 4.11.0 (https://pypi.org/project/ydata-profiling/), so there is something happening with the anaconda repo. 

I'll check with the team, but I do suggest that you use Pypi instead for the time being.

**Comment by fabclmnt** [comment]
@stefansimik conda-forge is now fixed: https://anaconda.org/conda-forge/ydata-profiling

**Comment by stefansimik** [comment]
> @stefansimik conda-forge is now fixed: https://anaconda.org/conda-forge/ydata-profiling

Excellent work 👍 , I really appreciate your effort and how fast you solved this ❤️

**Comment by juansecal** [comment]
I'm getting ImportError: Numba needs NumPy 2.0 or less. Got NumPy 2.2. in the last release, is this normal =?

**Comment by NathanHGayle** [comment]
Getting the same issue as above

**Comment by b4ghir1** [comment]
Get the same error: 
`Import Error: Numba needs NumPy 2.0 or less. Got NumPy 2.2.`

Version: 
```
numba                     0.60.0
numpy                     2.0.2
ydata-profiling           4.12.1
```

From this line: 
`from ydata_profiling import ProfileReport`
