### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SweBai** [ydataai/ydata-profiling#1661]
### Missing functionality

export to pdf or excel/csv than html
ways to summarize the alerts like 50 cols (50%) have missing greater than 10%, 25% etc
there are 20 cols that are unsupported .. something like that 

### Proposed feature

data quality summary report

**Comment by gmartinsribeiro** [comment]
Hi @SweBai , that's indeed a very important aspect to measure! Really appreciate pointing that out.
Have your tried Fabric already?
The missing functionality you're asking for is already supported by Fabric, which is also free to use: https://ydata.ai/register

Let me know your feedback about it!
