### ISSUE TITLE
Support for PySpark / Spark dataframes?

### ISSUE THREAD

**Issue by steven-struglia** [ydataai/ydata-profiling#543]
Would be super great to have PySpark / Spark dataframe functionality for this package as our team is using Spark as our scalable backend. 

Thanks so much!

**Comment by sbrugman** [comment]
Planned for end of this year. Any contributions are welcome.

**Comment by skorski** [comment]
is there a branch for this or an implementation plan?

**Comment by sbrugman** [comment]
@skorski There is currently no branch for this. here used to be a version of PP that was executing a Spark backend. That implementation used the `pyspark.sql` module to generate the statistics. Feel welcome to contribute if you'd like.

ps. (PNNL in) Richland rang a bell, turns out we passed it when visiting Gravity Hill

**Comment by sbrugman** [comment]
The working document for the implementation plan can be found here: https://github.com/pandas-profiling/pandas-profiling/wiki/Spark-Development-Plan. Contributions are welcome.

(Thanks to @chanedwin)

**Comment by skorski** [comment]
@sbrugman The implementation plan is looking really good.  I'll try to dig into it a bit and help where I can.  Where is the best place to post questions?

**Comment by ahmedanis03** [comment]
What about leveraging [koalas](https://koalas.readthedocs.io/en/latest/) ?, this would be a huge shortcut?

**Comment by sbrugman** [comment]
@skorski The Slack community for pandas-profiling can be used for that:
https://join.slack.com/t/pandas-profiling/shared_invite/zt-hfy3iwp2-qEJSItye5QBZf8YGFMaMnQ

@ahmedanis03 Thank you for the suggestion, we're also considering koalas. The bulk of the work seems to be in refactoring and specific features more or less regardless of API (correlations, missing diagrams).

**Comment by test32443** [comment]
There is already a project that was built around porting pandas-profiling to Spark: https://github.com/julioasotodv/spark-df-profiling
I wonder if its code base could be of any help.

**Comment by geoHeil** [comment]
What about simply replacing pandas with koalas? https://github.com/databricks/koalas? Maybe it is worth a shot?

**Comment by dclong** [comment]
I used to develop a big data profiling library based on Spark and also explored for such good open source solutions. Later, when I came across pandas-profiling, I give us other solutions and have been quite happy with pandas-profiling. I have been using pandas-profiling to profile large production too. The simple trick is to randomly sample data from Spark cluster and get it to one machine for data profiling using pandas-profiling. Do we really need to profile on the whole large data? For most non-extreme metrics, the answer is no. A 100K row will likely give you accurate enough information about the population. For extreme metrics such as max, min, etc., I calculated them by myself. 

If pandas-profiling is going to support profiling large data, this might be the easiest but good-enough way. Just my 2 cents.

**Comment by fanzhuyifan** [comment]
Is there a development branch for this if we want to contribute?

**Comment by ncoish** [comment]
Hey all, is there any ongoing development for this Spark backend? We're thinking of adopting this tool, but as our datasets grow we're eventually going to have to use Spark for our profiling.

**Comment by sbrugman** [comment]
Hey @ncoish, yes it's ongoing ! @chanedwin has done the lion's share of the work needed for the Spark backend, which now needs to be integrated

**Comment by sonusourabh** [comment]
> Hey @ncoish, yes it's ongoing ! @chanedwin has done the lion's share of the work needed for the Spark backend, which now needs to be integrated 

Few more weeks/months of wait?

**Comment by kyprifog** [comment]
I would also like to know where this code lives so I can help out.  One thing I would like to put forth to be considered is being able to pull out the underlying queries that form the profiles into spark to avoid pulling all of pandas-profiling for people that just want to be able to get that part of it and not the whole package.

**Comment by sbrugman** [comment]
https://github.com/pandas-profiling/pandas-profiling/pull/670

**Comment by araker** [comment]
Hi, how is this progressing? I see in the 'spark development plan' that the plan is to release early December 2021, is that still the expectation?

**Comment by sbrugman** [comment]
The progress can be tracked on the github project. An alpha version is planned December 2021. In case anyone is interested in contributing, please reach out to @chanedwin (preferably via our Slack channel)

**Comment by chanedwin** [comment]
hello! yup, echoing what Simon has said, hoping to get an alpha release down sometime in December (or latest early Jan, if things get messier than expected). Please feel free to join the slack channel if you would like to get involved - always happy to discuss more there!

**Comment by DataRx** [comment]
Appreciate the effort in getting this to work with Spark.  Any updates?

**Comment by DataRx** [comment]
I fear this endeavor has gone stale.

**Comment by daherk2** [comment]
I would like to be a beta tester of this feature :-)

**Comment by PraJaL55** [comment]
Is someone still working on this feature?

**Comment by Gexar** [comment]
No news so far?

**Comment by eyaldahari** [comment]
Looking forward to have this feature released. Also if needed a beta tester and contribute.

**Comment by rivanfebrian123** [comment]
Can we use [Koalas](https://koalas.readthedocs.io/en/latest/) as a "backend"?

**Comment by araker** [comment]
@sbrugman , @chanedwin , is this feature really still in development? It seems stale / abandoned to me. Would be nice that expectations are managed here.

**Comment by fabclmnt** [comment]
@araker and @akshat-um  this is not an abandoned feature, it is still in development. 

We expected to have new very soon, so stay tuned :) You can follow-up more closely the updates around the package through our [Discord](https://discord.gg/mw7xjJ7b7s).

**Comment by guanjieshen** [comment]
Hi @fabclmnt would be happy to help with adding Spark support!

**Comment by fabclmnt** [comment]
Hi @guanjieshen great to know! We are preparing the [Spark-Profiling roadmap](https://github.com/orgs/ydataai/projects/15/views/1) here, **WIP** that will be completed soon :) 

Soon the first version will be released, but the following issue I think is the most relevant to start with are the following:
- #869 
- #878 

But there are a couple more :)

**Comment by xrh** [comment]
What is the latest update for supporting Pyspark dataframes ?  I tried recently, it's still not supporting Pyspark dataframes. I have covert the Pyspark dataframe to Pandas dataframe before using this package.
