### ISSUE TITLE
.to_json and ._render_json do not return data under "Toggle details" tab

### ISSUE THREAD

**Issue by VikrantMN26** [ydataai/ydata-profiling#605]
We use both the html report and the json output in our projects. However, a few things present in the html report seem to be missing in the json output. Specifically, the data from the "Toggle Details" tab under every variable is missing in the json output.

**To Reproduce**
import pandas as pd
from pandas_profiling import ProfileReport

def test_issueXXX():
    df = pd.read_csv(r'<file>',encoding="unicode_escape")
    prof = ProfileReport(df)
    return prof._render_json()
 

**Version information:**
Python version - 3.7.9
pandas-profiling version : 2.9.0

**Comment by loopyme** [comment]
I believe this part of data is in the json (maybe wrong)

Since the json structure is kind of complex, read this function may help you understand it
https://github.com/pandas-profiling/pandas-profiling/blob/87d964c1e5a20461002c27a2861f7ea1ba742c93/src/pandas_profiling/model/describe.py#L24

**Comment by sbrugman** [comment]
@VikrantMN26 We've changed the json respresentation a bit (still could be simplified more even). If you're still encountering this issue, could you please give an example of a specific field missing for a given dataset (for instance from the examples section)?
