### ISSUE TITLE
Dump to Pickle using `ProfileReport.dump` fails silent

### ISSUE THREAD

**Issue by dclong** [ydataai/ydata-profiling#639]
**Describe the bug**

I profiled a large pandas DataFrame and tried to dump the report into HTML, JSON and pickle. It successfully dumped the report into HTML and JSON files but it failed silent when dumping into pickle. Basically, no pickle file was generated and no error was thrown either. 

**To Reproduce**

 

**Version information:**

Python: 3.8.5
Env: command line
pandas-profiling: 2.9.0

**Additional context**

**Comment by sbrugman** [comment]
@dclong Thanks for reporting. Could you share the code example you're using?

**Comment by dclong** [comment]
@sbrugman Sorry that I didn't provided reproducible steps. I couldn't share the data here. I will make some fake data and try to reproduce the issue based on the fake data. Will update this thread later.

**Comment by dclong** [comment]
I think the issue was caused by out of memory issue. I encounter the issue issue dumping JSON report for a larger data frame. If this is indeed caused by out of memory issue, a MemoryError or so should be thrown rather than failing silently.
